#!/usr/bin/perl

# process medpc datafile. 
# this version 2010-01-17 does not process the E, F, G, H data (timing of the events) 


if ($ARGV[0]){
	$DirName=$ARGV[0];
	$DirName=~s/\/$//;
} else {
	print "using default destination folder ";
	$DirName="/home/hao/Dropbox/HaoLabShare/rawdata/";
	chomp($DirName);
	$DirName=~s/\/$//;
}

print "$DirName\n";

#system ("cp -v `find /home/hao/Dropbox/HaoLabShare/rawdata/ -mtime -1 -print` $DirName");
#system ("mv -uv `find /home/hao/data/saccNicSA/ns030Data/ -mtime +60 -name \"*Subject*\"` /home/hao/data/saccNicSA/rawDataBackup");
system ("mv -uv `find /home/hao/Dropbox/HaoLabShare/rawdata/ -mtime +60 -name \"*Subject*\"` /home/hao/inbox\@haochen.name/rawData/");
open (OUT, ">$DirName.csv");
open (W, ">/home/hao/Documents/data/saccNicSA/bodyweight.tmp.csv");

print OUT "zdate\tStart_time\tEID\tBox\tAID\tweight\tlength\tschedule\tsacclick\twaterlick\tsaccdrop\twaterdrop\tsaccconc\tsa_drug\tdemo\tnote\tDemoLick\tOBpoke\tDmPoke\n";

opendir(DIR, $DirName) || die "Could not find directory $DirName";


rewinddir(DIR);

@FileNames = readdir(DIR);
@FileNames = sort (@FileNames);
closedir(DIR);
$date="";
foreach $file (@FileNames) {
	#print "$DirName/$file\n";
	open(F, "$DirName/$file") || die;
	while (<F>) {
		$cmt="";
		$_=~s/\r//;

		$date=$1 if ($_=~/Start Date:\s+(\d\d\/\d\d\/\d\d)/) ;
		$subj=$1 if $_=~/Subject:\s+(\w.+)/;
		$subj=$1 if $_=~/Subject:\s+(\#.+)/;
		$subj=~s/ //g;
		$exp=$1 if $_=~/Experiment:\s+(\w.+)/;
		$time=$1 if $_=~/Start Time:\s+(\d+:\d\d:\d\d)/;
		$Box=$1 if $_=~/^Box:\s+(\d+)/;
		$A=$1 if $_=~/^A:\s+(\d+)\./;
		$B=$1 if $_=~/^B:\s+(\d+)\./;
		$C=$1 if $_=~/^C:\s+(\d+)\./;
		$D=$1 if $_=~/^D:\s+(\d+)\./;
		$J=$1 if $_=~/^J:\s+(\d+)\./;
		$K=$1 if $_=~/^K:\s+(\d+)\./;
		$R=$1 if $_=~/^R:\s+(\d+)\./;
		$P=$1 if $_=~/^P:\s+(\d+)\./;
		$Q=$1 if $_=~/^Q:\s+(\d+)\./;
		$S=$1 if $_=~/^S:\s+(\d+)\./;
		$W=$1 if $_=~/^W:\s+(\d+\.\d+)/;
		$W="" if ($W==120.001);
		if ($_=~/^\\(.*)/){ 
			$cmt=$1 ;
			$lastline=1;
		}
		$lastline=1	if ($_=~/^$/);
		#	$grp=$drug=$demo=$sacc='';
		if ($_=~/Group:\s+(\w.+)/){
			$grp=lc($1); 
			$drug=$1 if ($grp=~/(Nic\d+|sal|EtOH\d+)/i);
			$demo=$1 if ($grp=~/(solo|demo)/i);
			$demo=$1 if ($grp=~/(PSE|NSE)/i);
			$sacc=$1 if ($grp=~/(sac+\d+|water|cocoaonly)/i);

		}
		
		if ($lastline){
			
			if ($subj=~/^#/ ){ 
				$out.=$date."\t".$time."\t".$exp."\t".$Box."\t".$subj."\t".$W."\t".$S."\t".$R."\t".$A."\t".$B."\t".$C."\t$sacc\t$drug\t$demo\t$P\t$J\t$K\t\t$grp\t$cmt\n";
			} else {
				$out.=$date."\t".$time."\t".$exp."\t".$Box."\t".$subj."\t".$W."\t".$S."\t".$R."\t".$A."\t".$B."\t".$C."\t".$D."\t$sacc\t$drug\t$demo\t$grp\t$P\t$J\t$K\t$cmt\n"; 
			}
			print W "$date\t$subj\t$W\t$C\n"; #body weight
			$subj=$exp=$time=$grp=$Box=$A=$B=$C=$D=$J=$K=$R=$P=$W=$S=$cmt=$demo=$drug=$grp=$sacc=$Q=$lastline="";
		}

	}
	close (F);

}

#		$out.="end".$date."\t".$subj."\t".$exp."\t".$grp."\t".$A."\t".$B."\t".$C."\t".$D."\t".$cmt."\n" ;

print OUT $out;
#print $out;
system("cut -f 1 $DirName.csv |grep -v ate|sort |uniq >>$DirName.csv");
system("sort -k1,1r -k3,3 -k5,5  $DirName.csv >> tmp.csv");
system("mv tmp.csv $DirName.csv");
system ("sort /home/hao/Documents/data/saccNicSA/bodyweight.tmp.csv > /home/hao/Documents/data/saccNicSA/bodyweight.csv");

if ($ARGV[1] ne 'nosoffice') {
system("soffice --calc $DirName.csv &");
}
